export enum TRANSITION_EVENT {
  FADE_IN_START = 'TRANSITION_FADE_IN_START',
  FADE_IN_END = 'TRANSITION_FADE_IN_END',
  FADE_OUT_START = 'TRANSITION_FADE_OUT_START',
  FADE_OUT_END = 'TRANSITION_FADE_OUT_END',
}

export enum TRANSITION_VALUE {
  DURATION = 0.3
}